const allRiders = [
  "Francesco Bagnaia #1",
  "Johann Zarco #5",
  "Luca Marini #10",
  "Maverick Viñales #12",
  "Fabio Quartararo #20",
  "Franco Morbidelli #21",
  "Enea Bastianini #23",
  "Raul Fernandez #25",
  "Iker Lecuona #27",
  "Takaaki Nakagami #30",
  "Lorenzo Savadori #32",
  "Brad Binder #33",
  "Joan Mir #36",
  "Augusto Fernandez #37",
  "Aleix Espargaro #41",
  "Alex Rins #42",
  "Jack Miller #43",
  "Pol Espargaro #44",
  "Fabio Di Giannantonio #49",
  "Marco Bezzecchi #72",
  "Alex Marquez #73",
  "Miguel Oliveira #88",
  "Jorge Martin #89",
  "Marc Marquez #93",
  "Jonas Folger #94",
];

export default allRiders;
